bug fix:
in latest codex version, it met:
```
$ codex exec resume --last "aaa"
error: the argument '--last' cannot be used with '[SESSION_ID]'

Usage: codex exec resume --last [SESSION_ID] [PROMPT]
```

the reason is that the exec resum subcmd recognize the first argument as the SESSION_ID,
rather than PROMPT, I fixed it by move the SESSION_ID arg field to the after of the PROMPT.

Signed-off-by: Mike Tang <daogangtang@gmail.com>